name: Sa11y
on: [push]
jobs:
  sa11y-jest:
    env:
      SA11Y_AUTO: 1
      SA11Y_CLEANUP: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Determine Node Version
        id: node-version
        run: |
          echo "::set-output name=ver::$(node --version)"
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ steps.node-version.outputs.ver }}-${{ hashFiles('package.json', 'yarn.lock') }}
      - name: Install Packages
        run: |
          yarn install
      - name: Run Jest Tests
        run: |
          npx lwc-jest --skipApiVersionCheck
